[package]
name = "cosmic-term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alacritty_terminal = "0.19"
bytemuck = "1.14"
env_logger = "0.10"
log = "0.4"
tiny-skia = "0.11"

[dependencies.cosmic-text]
git = "https://github.com/pop-os/cosmic-text.git"
branch = "refactor"

[dependencies.glyphon]
git = "https://github.com/jackpot51/glyphon.git"
branch = "refactor"
optional = true

[dependencies.pollster]
version = "0.3"
optional = true

[dependencies.softbuffer]
git = "https://github.com/pop-os/softbuffer.git"
branch = "cosmic"

[dependencies.wgpu]
version = "0.18"
optional = true

[dependencies.winit]
git = "https://github.com/pop-os/winit.git"
branch = "master"

[features]
default = []
wgpu = ["dep:glyphon", "dep:pollster", "dep:wgpu"]
