[package]
name = "cosmic-term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alacritty_terminal = "0.19"
env_logger = "0.10"
log = "0.4"
tokio = { version = "1.35", features = ["sync"] }

[dependencies.cosmic-text]
git = "https://github.com/pop-os/cosmic-text.git"
branch = "refactor"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["tokio", "winit"]

[features]
default = ["wgpu"]
wgpu = ["libcosmic/wgpu"]
