[package]
name = "cosmic-term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alacritty_terminal = "0.19"
softbuffer = "0.4"
tiny-skia = "0.11"
winit = "0.29"

[dependencies.cosmic-text]
git = "https://github.com/pop-os/cosmic-text.git"
branch = "refactor"
